### ISSUE TITLE
mod (simple hats) is crashing with (curios) in 1.20.1

### ISSUE THREAD

**Issue by gustxst** [fonnymunkey/SimpleHats#60]
every time i try to equip a hat minecraft crashes

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-04-21 08:10:04
Description: Unexpected error

java.lang.NoSuchMethodError: 'java.util.Map top.theillusivec4.curios.mixin.CuriosImplMixinHooks.getEntitySlots(net.minecraft.world.entity.EntityType)'
	at top.theillusivec4.curios.mixin.CuriosImplMixinHooks.handler$zbo000$simplehats_getItemStackSlots(CuriosImplMixinHooks.java:543) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:APP:mixins.simplehats.json:MixinCuriosImplMixinHooks,pl:mixin:A}
	at top.theillusivec4.curios.mixin.CuriosImplMixinHooks.getItemStackSlots(CuriosImplMixinHooks.java:78) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:APP:mixins.simplehats.json:MixinCuriosImplMixinHooks,pl:mixin:A}
	at top.theillusivec4.curios.mixin.CuriosImplMixinHooks.isStackValid(CuriosImplMixinHooks.java:119) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:APP:mixins.simplehats.json:MixinCuriosImplMixinHooks,pl:mixin:A}
	at top.theillusivec4.curios.api.CuriosApi.handler$zbd000$curios$isStackValid(CuriosApi.java:644) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:A}
	at top.theillusivec4.curios.api.CuriosApi.isStackValid(CuriosApi.java) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:A}
	at top.theillusivec4.curios.common.inventory.DynamicStackHandler.isItemValid(DynamicStackHandler.java:72) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$curioRightClick$22(CuriosEventHandler.java:397) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137) ~[forge-1.20.1-47.2.30-universal.jar%23191!/:?] {re:classloading,re:mixin}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$curioRightClick$23(CuriosEventHandler.java:384) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137) ~[forge-1.20.1-47.2.30-universal.jar%23191!/:?] {re:classloading,re:mixin}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.curioRightClick(CuriosEventHandler.java:383) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading}
	at top.theillusivec4.curios.common.event.__CuriosEventHandler_curioRightClick_RightClickItem.invoke(.dynamic) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:771) ~[forge-1.20.1-47.2.30-universal.jar%23191!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233716_(MultiPlayerGameMode.java:363) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233721_(MultiPlayerGameMode.java:356) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.m_233721_(PlayerControllerOF.java:80) ~[preview_OptiFine_1.20.1_HD_U_I6_pre6.jar%23196!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1720) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[gggggg.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.30.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.30.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.30.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at top.theillusivec4.curios.mixin.CuriosImplMixinHooks.handler$zbo000$simplehats_getItemStackSlots(CuriosImplMixinHooks.java:543) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:APP:mixins.simplehats.json:MixinCuriosImplMixinHooks,pl:mixin:A}
	at top.theillusivec4.curios.mixin.CuriosImplMixinHooks.getItemStackSlots(CuriosImplMixinHooks.java:78) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:APP:mixins.simplehats.json:MixinCuriosImplMixinHooks,pl:mixin:A}
	at top.theillusivec4.curios.mixin.CuriosImplMixinHooks.isStackValid(CuriosImplMixinHooks.java:119) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:APP:mixins.simplehats.json:MixinCuriosImplMixinHooks,pl:mixin:A}
	at top.theillusivec4.curios.api.CuriosApi.handler$zbd000$curios$isStackValid(CuriosApi.java:644) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:A}
	at top.theillusivec4.curios.api.CuriosApi.isStackValid(CuriosApi.java) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:mixin,re:classloading,pl:mixin:A}
	at top.theillusivec4.curios.common.inventory.DynamicStackHandler.isItemValid(DynamicStackHandler.java:72) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$curioRightClick$22(CuriosEventHandler.java:397) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137) ~[forge-1.20.1-47.2.30-universal.jar%23191!/:?] {re:classloading,re:mixin}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$curioRightClick$23(CuriosEventHandler.java:384) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137) ~[forge-1.20.1-47.2.30-universal.jar%23191!/:?] {re:classloading,re:mixin}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.curioRightClick(CuriosEventHandler.java:383) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading}
	at top.theillusivec4.curios.common.event.__CuriosEventHandler_curioRightClick_RightClickItem.invoke(.dynamic) ~[curios-forge-5.8.1+1.20.1.jar%23177!/:5.8.1+1.20.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:771) ~[forge-1.20.1-47.2.30-universal.jar%23191!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233716_(MultiPlayerGameMode.java:363) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233721_(MultiPlayerGameMode.java:356) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.m_233721_(PlayerControllerOF.java:80) ~[preview_OptiFine_1.20.1_HD_U_I6_pre6.jar%23196!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1720) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['GgKljs'/51, l='ClientLevel', x=-3.70, y=-60.00, z=9.38]]
	Chunk stats: 361, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1071 game time, 1071 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:590) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[gggggg.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.30.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.30.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.30.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1692217072 bytes (1613 MiB) / 2852126720 bytes (2720 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 3.09
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce 9500 GT
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x0640
	Graphics card #0 versionInfo: DriverVersion=21.21.13.4201
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 12526.59
	Virtual memory used (MB): 7284.65
	Swap memory total (MB): 6400.00
	Swap memory used (MB): 197.48
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6122M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: gggggg
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: GeForce 9500 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	Window size: 925x530
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: pt_pt
	CPU: 4x Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['GgKljs'/51, l='ServerLevel[Novo mundo]', x=-3.70, y=-60.00, z=9.38]]
	Data Packs: vanilla, mod:configured (incompatible), mod:cyclopscore, mod:bcc (incompatible), mod:commoncapabilities, mod:resourcefullib (incompatible), mod:cupboard (incompatible), mod:jei, mod:resourcefulconfig (incompatible), mod:cloth_config (incompatible), mod:forge, mod:curios (incompatible), mod:tlskincape (incompatible), mod:simplehats (incompatible), mod:spark (incompatible), mod:notenoughcrashes (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.20.1_HD_U_I6_pre6
	OptiFine Build: 20230727-130058
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0
	OpenGlRenderer: GeForce 9500 GT/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		configured-forge-1.20.1-2.2.3.jar                 |Configured                    |configured                    |2.2.3               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		CyclopsCore-1.20.1-1.19.1.jar                     |Cyclops Core                  |cyclopscore                   |1.19.1              |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-4.4.7+1.20.1-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.4.7+1.20.1        |DONE      |Manifest: NOSIGNATURE
		BetterCompatibilityChecker-neo-4.0.8+mc1.20.1.jar |Better Compatibility Checker  |bcc                           |4.0.8               |DONE      |Manifest: NOSIGNATURE
		CommonCapabilities-1.20.1-2.9.1.jar               |CommonCapabilities            |commoncapabilities            |2.9.1               |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.24.jar            |Resourceful Lib               |resourcefullib                |2.1.24              |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.6.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.6          |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.3.0.4.jar                     |Just Enough Items             |jei                           |15.3.0.4            |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.2.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.2               |DONE      |Manifest: NOSIGNATURE
		spark-1.10.53-forge.jar                           |spark                         |spark                         |1.10.53             |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.30-universal.jar                |Forge                         |forge                         |47.2.30             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		curios-forge-5.8.1+1.20.1.jar                     |Curios API                    |curios                        |5.8.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.20_1.20.1-1.32.jar           |TLSkinCape                    |tlskincape                    |1.32                |DONE      |Manifest: ef:fe:e7:59:91:bb:3a:06:c1:94:f4:f3:9c:3e:26:69:47:fa:2e:c5:53:d3:38:21:65:cc:04:75:e7:61:19:40
		simplehats-forge-1.20.1-0.2.2.jar                 |SimpleHats                    |simplehats                    |1.20.1-0.2.2        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f5d30738-2acc-40dd-b10b-8647e723a0cb
	FML: 47.2
	Forge: net.minecraftforge:47.2.30
	Suspected Mods: Curios API (curios), SimpleHats (simplehats), Minecraft (minecraft), Forge (forge)

I have no idea how to solve this

**Comment by fonnymunkey** [comment]
You're using SimpleHats 0.2.2, update to 0.2.4
